ingress:
  enabled: false
  annotations: {}
  path: /
  hosts:
    - test.example.com
  tls: []

myweb:
  env:
    name: test123
  service:
    port: 8080
    targetPort: 8080
    type: NodePort
  image:
    repository: tomcat
    tag: 8
