apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  labels:
    app: my-web
    release: {{ .Release.Name }}
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: my-web
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: my-web
        release: "{{ .Release.Name }}"

    spec:
      containers:
        - name: my-web
          image: "{{ .Values.myweb.image.repository }}:{{ .Values.myweb.image.tag }}"
          env:
            - name: MY_NAME
              value: "lucas"
          ports:
            - containerPort: 8080
