apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-my-web
  labels:
    app: my-web
    release: {{ .Release.Name }}
spec:
  ports:
    - port: {{ .Values.my-web.service.port }}
      targetPort:  {{ .Values.my-web.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    app: my-web
    release:  {{ .Release.Name }}
  type: {{ .Values.my-web.service.type }}
